version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Vessel_API
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5433"
    networks:
      - my-network

  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
